services:
  - type: web
    name: swastha-backend
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    workingDirectory: backend/flask-api
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9